//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHAMMED_ABDULLAH_P00193895_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRide
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<decimal> Charge { get; set; }
    }
}
