//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHAMMED_ABDULLAH_P00193895_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRestaurant
    {
        public int Id { get; set; }
        public string Table_Size { get; set; }
        public decimal Charge { get; set; }
    }
}
