//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOHAMMED_ABDULLAH_P00193895_Booking
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int Id { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> isPublic { get; set; }
        public string reviewDate { get; set; }
    }
}
